site_name: My Docs 2
site_url: 'https://anton-merkulov.github.io/mkdocs/'
theme:
  name: material
  custom_dir: overrides

plugins:
  - search
  - with-pdf

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
    

extra:
  version:
    provider: mike
