site_name: My Docs 2
site_url: 'https://anton-merkulov.github.io/mkdocs/'
theme:
  name: material
  custom_dir: overrides

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version:
    provider: mike
